[FIXING] the bash in charge of checking the files and their status

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -16,6 +16,7 @@ env:
   EXECUTABLE: "hello_world"
   EPITEST_DOCKER: ghcr.io/epitech/coding-style-checker:latest
   GITHUB_SSH_KEY: ${{ secrets.MY_CHOCO_PRIVATE_SSH_KEY }}
+  CHECKER: check_results_v2.sh
 
 jobs:
   check_coding_style:
@@ -30,19 +31,17 @@ jobs:
     - name: run check.sh
       run: ./check.sh $(pwd) $(pwd)
     - name: checking the results
-      # run: chmod +x ./check_results.sh && ./check_results.sh
-      run: |
-        CONTENT="$(cat coding-style-reports.log)"
-        ILLEGAL_FILES_FOUND=0
-        for FILE in $CONTENT; do
-            echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
-            ILLEGAL_FILES_FOUND=1
-        done
-        if [ $ILLEGAL_FILES_FOUND -eq 1 ]; then
-            exit 1
-        else
-            echo "::success file='',line=1,endLine=0,title=No Unwanted file detected::"
-        fi
+      run: chmod +x ./${{ CHECKER }} && ./${{ CHECKER }}
+      # run: |
+      #   CONTENT="$(cat coding-style-reports.log)"
+      #   ILLEGAL_FILES_FOUND=0
+      #   for FILE in $CONTENT; do
+      #       echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
+      #       ILLEGAL_FILES_FOUND=1
+      #   done
+      #   if [ $ILLEGAL_FILES_FOUND -eq 1 ]; then
+      #       exit 1
+      #   fi
 
   repository_mirroring:
     runs-on: ubuntu-latest
